#!/usr/bin/php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$inputPath = $argv[1];

$plop = new \Aternos\Plop\Plop(\Aternos\Plop\Input\StructureFile\StructureFile::loadFile($inputPath), functionName: 'plop:silo');
$plop->generate();

echo $plop->getOutput()->getAsString();